name: Semantic release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Node environment
        uses: actions/setup-node@v1
        with:
          node-version: "10.18.0"
      - name: Install dependencies
        run: npm ci
      - name: Create dist/ folder
        run: mkdir dist/
      - name: Run browserify
        run: npm run browserify
      - name: Run browserify-min
        run: npm run browserify-min
      - name: Release new verion
        env:
          NPM_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
        run: npx semantic-release
